### ISSUE TITLE
ToDo's for W3C Workshop / F2F in Munich

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#88]
Sticky placeholder to keep track of items we need to work on for upcoming [W3C workshop](https://www.w3.org/WoT/ws-2019/cfp.html) and F2F in Munich, June 2019.

- [ ] Update node-wot with *latest* Scripting API definitions (see https://w3c.github.io/wot-scripting-api/)
  - [ ] FYI: Work takes place in dedicated [`next-api-2019`](https://github.com/eclipse/thingweb.node-wot/tree/next-api-2019) branch till it is merged
  - [ ] Update TypeScript definitions
  - [ ] Update eventing (remove observable, ...)
  - [ ] Alignments with https://w3c.github.io/wot-thing-description/ needed ?
  - [ ] ...
- [ ] Align/update testing examples with new API
- [ ] Takeover from *old* issue https://github.com/eclipse/thingweb.node-wot/issues/56
  - [ ] Eventing in general: `cancellation`, `subscription`, ...
  - [ ] `ExpectedResponse` (@wiresio)

**Comment by sebastiankb** [comment]
> @language (@danielpeintner: Is there anything special about it?)

Maybe this here (from TD spec): 'Another possibility to set the default language is through a language negotiation mechanism, such as the Accept-Language header field of HTTP. In cases where the default language has been negotiated, an @language member MUST be present to indicate the result of the negotiation and the corresponding default language of the returned content. '

**Comment by egekorkan** [comment]
@danielpeintner regarding:
>  http namespace included in context (prefix htv is there by default, related with #80)

It seems that the current version doesn't add `htv:methodName` in forms at all. Before it was at least adding `http:methodName` ?

**Comment by danielpeintner** [comment]
> It seems that the current version doesn't add htv:methodName in forms at all. Before it was at least adding http:methodName ?

@egekorkan Please have a look at the recent commits. Does this resolve the issue?

However, `htv:methodName` is somewhat limited. Let's assume one uses op field with `[readproperty, writeproperty]` one cannot set a *single* htv:methodName.

Hence I only set
* `GET` for htv:methodName in case of readproperty only
* `PUT` for htv:methodName in case of writeproperty only
* `POST` for htv:methodName in case of invokeaction (any action)

**Comment by egekorkan** [comment]
@danielpeintner the last commit has fixed the issue, thanks! The new issue you wrote also points out to something interesting :)

**Comment by danielpeintner** [comment]
workshop is over by now
https://www.w3.org/WoT/ws-2019/cfp.html
